[2024-01-08T04:40:36.714+0000] {processor.py:161} INFO - Started process (PID=67) to work on /opt/airflow/dags/index_data/index_to_es.py
[2024-01-08T04:40:36.716+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_to_es.py for tasks to queue
[2024-01-08T04:40:36.717+0000] {logging_mixin.py:188} INFO - [2024-01-08T04:40:36.717+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_to_es.py
[2024-01-08T04:40:38.235+0000] {logging_mixin.py:188} INFO -              GAME_DATE_EST   GAME_ID  ... REB_away  HOME_TEAM_WINS
0               2022-03-12  22101005  ...     46.0               0
1               2022-03-12  22101006  ...     40.0               1
2               2022-03-12  22101007  ...     47.0               0
3               2022-03-12  22101008  ...     39.0               1
4               2022-03-12  22101009  ...     50.0               0
...                    ...       ...  ...      ...             ...
27758  2023-10-28 00:00:00  22300091  ...     48.0               0
27759  2023-10-28 00:00:00  22300088  ...     33.0               1
27760  2023-10-28 00:00:00  22300094  ...     45.0               1
27761  2023-10-28 00:00:00  22300093  ...     42.0               1
27762  2023-10-28 00:00:00  22300092  ...     42.0               0

[27763 rows x 21 columns]
[2024-01-08T04:40:38.236+0000] {logging_mixin.py:188} INFO - Indexing into http://elasticsearch:9200 with index test_data_ds
[2024-01-08T04:41:06.739+0000] {logging_mixin.py:188} INFO - [2024-01-08T04:41:06.732+0000] {timeout.py:68} ERROR - Process timed out, PID: 67
[2024-01-08T04:41:06.749+0000] {logging_mixin.py:188} INFO - [2024-01-08T04:41:06.748+0000] {_transport.py:358} INFO - PUT http://elasticsearch:9200/test_data_ds/_bulk [status:N/A duration:28.297s]
[2024-01-08T04:41:06.754+0000] {logging_mixin.py:188} INFO - [2024-01-08T04:41:06.754+0000] {_node_pool.py:249} WARNING - Node <Urllib3HttpNode(http://elasticsearch:9200)> has failed for 1 times in a row, putting on 1 second timeout
[2024-01-08T04:41:06.765+0000] {logging_mixin.py:188} INFO - [2024-01-08T04:41:06.758+0000] {_transport.py:395} WARNING - Retrying request after failure (attempt 0 of 3)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/elastic_transport/_transport.py", line 328, in perform_request
    meta, raw_data = node.perform_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/elastic_transport/_node/_http_urllib3.py", line 202, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: AirflowTaskTimeout(DagBag import timeout for /opt/airflow/dags/index_data/index_to_es.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.8.0/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.8.0/best-practices.html#reducing-dag-complexity, PID: 67)
[2024-01-08T04:41:57.548+0000] {processor.py:161} INFO - Started process (PID=241) to work on /opt/airflow/dags/index_data/index_to_es.py
[2024-01-08T04:41:57.551+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_to_es.py for tasks to queue
[2024-01-08T04:41:57.554+0000] {logging_mixin.py:188} INFO - [2024-01-08T04:41:57.553+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_to_es.py
[2024-01-08T04:41:57.872+0000] {logging_mixin.py:188} INFO -              GAME_DATE_EST   GAME_ID  ... REB_away  HOME_TEAM_WINS
0               2022-03-12  22101005  ...     46.0               0
1               2022-03-12  22101006  ...     40.0               1
2               2022-03-12  22101007  ...     47.0               0
3               2022-03-12  22101008  ...     39.0               1
4               2022-03-12  22101009  ...     50.0               0
...                    ...       ...  ...      ...             ...
27758  2023-10-28 00:00:00  22300091  ...     48.0               0
27759  2023-10-28 00:00:00  22300088  ...     33.0               1
27760  2023-10-28 00:00:00  22300094  ...     45.0               1
27761  2023-10-28 00:00:00  22300093  ...     42.0               1
27762  2023-10-28 00:00:00  22300092  ...     42.0               0

[27763 rows x 21 columns]
[2024-01-08T04:41:57.874+0000] {logging_mixin.py:188} INFO - Indexing into http://elasticsearch:9200 with index test_data_ds
[2024-01-08T04:42:27.571+0000] {logging_mixin.py:188} INFO - [2024-01-08T04:42:27.565+0000] {timeout.py:68} ERROR - Process timed out, PID: 241
[2024-01-08T04:42:27.580+0000] {logging_mixin.py:188} INFO - [2024-01-08T04:42:27.579+0000] {_transport.py:358} INFO - PUT http://elasticsearch:9200/test_data_ds/_bulk [status:N/A duration:29.519s]
[2024-01-08T04:42:27.586+0000] {logging_mixin.py:188} INFO - [2024-01-08T04:42:27.585+0000] {_node_pool.py:249} WARNING - Node <Urllib3HttpNode(http://elasticsearch:9200)> has failed for 1 times in a row, putting on 1 second timeout
[2024-01-08T04:42:27.594+0000] {logging_mixin.py:188} INFO - [2024-01-08T04:42:27.588+0000] {_transport.py:395} WARNING - Retrying request after failure (attempt 0 of 3)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/elastic_transport/_transport.py", line 328, in perform_request
    meta, raw_data = node.perform_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/elastic_transport/_node/_http_urllib3.py", line 202, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: AirflowTaskTimeout(DagBag import timeout for /opt/airflow/dags/index_data/index_to_es.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.8.0/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.8.0/best-practices.html#reducing-dag-complexity, PID: 241)
[2024-01-08T04:43:17.787+0000] {processor.py:161} INFO - Started process (PID=413) to work on /opt/airflow/dags/index_data/index_to_es.py
[2024-01-08T04:43:17.790+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/index_data/index_to_es.py for tasks to queue
[2024-01-08T04:43:17.793+0000] {logging_mixin.py:188} INFO - [2024-01-08T04:43:17.793+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/index_data/index_to_es.py
[2024-01-08T04:43:18.134+0000] {logging_mixin.py:188} INFO -              GAME_DATE_EST   GAME_ID  ... REB_away  HOME_TEAM_WINS
0               2022-03-12  22101005  ...     46.0               0
1               2022-03-12  22101006  ...     40.0               1
2               2022-03-12  22101007  ...     47.0               0
3               2022-03-12  22101008  ...     39.0               1
4               2022-03-12  22101009  ...     50.0               0
...                    ...       ...  ...      ...             ...
27758  2023-10-28 00:00:00  22300091  ...     48.0               0
27759  2023-10-28 00:00:00  22300088  ...     33.0               1
27760  2023-10-28 00:00:00  22300094  ...     45.0               1
27761  2023-10-28 00:00:00  22300093  ...     42.0               1
27762  2023-10-28 00:00:00  22300092  ...     42.0               0

[27763 rows x 21 columns]
[2024-01-08T04:43:18.135+0000] {logging_mixin.py:188} INFO - Indexing into http://elasticsearch:9200 with index test_data_ds
